version: "3.5"

services:
  jekyll:
    build:
      context: ./
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
      - ./docs:/usr/src/app/docs
      - ./assets/images:/usr/src/app/assets/images
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t
